name: Daily Auto Checkin

on:
  schedule:
    # ┌───────────── minute
    # │ ┌─────────── hour
    # │ │ ┌───────── day of month
    # │ │ │ ┌─────── month
    # │ │ │ │ ┌───── day of week (1-5 = Mon-Fri)
    - cron: '10 1 * * 1-5'   # 08:10 VN
    - cron: '50 11 * * 1-5'  # 18:50 VN
  workflow_dispatch:         # Manual trigger

jobs:
  checkin:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        attempt: [1, 2, 3]  # Retry up to 2 times
    steps:
      - name: Call Base.vn Check-in API (Attempt ${{ matrix.attempt }})
        run: |
          curl -X POST https://checkin.base.vn/ajax/api/me/checkin/web \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "client_id=215&content=&captcha=1aaef45&__code=a266018b05b81f06de39e1379530bc77&__sessionid=a9nv8k98e4vh42qdnc0cpsf3g80fv94mptcmq3ptri2kiopgg0bo4ei1o8vc76shamkj0jo266905afe&__otp=848586dd014d9cce463d5efba78af41e"
